CREATE DATABASE IF NOT EXISTS gcs;
USE gcs;

CREATE TABLE director (
    NAME VARCHAR(100) PRIMARY KEY,
    PHONE_NO VARCHAR(20),
    ADDRESS VARCHAR(255)
);

CREATE TABLE licenses (
    LIC_NO INT PRIMARY KEY,
    CITY VARCHAR(100) NOT NULL,
    DATE DATE NOT NULL,
    ISSUES VARCHAR(100) NOT NULL,
    COST DECIMAL(10,2) NOT NULL,
    DEPT VARCHAR(100) NOT NULL,
    CONTACT VARCHAR(100) NOT NULL
);

CREATE TABLE racer (
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    MEM_NUM VARCHAR(50),
    PRIMARY KEY (NAME, ADDRESS)
);

CREATE TABLE manufacturer (
    NAME VARCHAR(100) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    CONTACT VARCHAR(100) NOT NULL
);

CREATE TABLE race (
    R_NO INT,
    LIC_NO INT,
    DIR VARCHAR(100) NOT NULL,
    MAL_WIN_NAME VARCHAR(100) NOT NULL,
    MAL_WIN_ADDRESS VARCHAR(255) NOT NULL,
    FEM_WIN_NAME VARCHAR(100) NOT NULL,
    FEM_WIN_ADDRESS VARCHAR(255) NOT NULL,
    SP_NAME VARCHAR(100),

    PRIMARY KEY(R_NO, LIC_NO),
    FOREIGN KEY (LIC_NO) REFERENCES licenses(LIC_NO),
    FOREIGN KEY (DIR) REFERENCES director(NAME),
    FOREIGN KEY (SP_NAME) REFERENCES manufacturer(NAME),
    FOREIGN KEY (MAL_WIN_NAME, MAL_WIN_ADDRESS) REFERENCES racer(NAME, ADDRESS),
    FOREIGN KEY (FEM_WIN_NAME, FEM_WIN_ADDRESS) REFERENCES racer(NAME, ADDRESS)
);

CREATE TABLE race_racer (
    R_NO INT,
    RACER_NAME VARCHAR(100),
    RACER_ADDRESS VARCHAR(255),
    PRIMARY KEY (R_NO, RACER_NAME, RACER_ADDRESS),
    FOREIGN KEY (R_NO) REFERENCES race(R_NO),
    FOREIGN KEY (RACER_NAME, RACER_ADDRESS) REFERENCES racer(NAME, ADDRESS)
);

CREATE TABLE shoes (
    MODEL VARCHAR(255),
    SIZE VARCHAR(50),
    PRIMARY KEY (MODEL, SIZE)
);

CREATE TABLE distributor  (
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    SIN VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (NAME, ADDRESS)
);

CREATE TABLE salesperson (
    SIN VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    COMMISSION DECIMAL(5, 2)
);

CREATE TABLE makes (
    MANUFACTURER_NAME VARCHAR(100) NOT NULL,
    SHOES_MODEL VARCHAR(255) NOT NULL,
    SHOES_SIZE VARCHAR(50) NOT NULL,
    PROD_COST DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (MANUFACTURER_NAME, SHOES_MODEL, SHOES_SIZE),
    FOREIGN KEY (MANUFACTURER_NAME) REFERENCES manufacturer(NAME),
    FOREIGN KEY (SHOES_MODEL, SHOES_SIZE) REFERENCES shoes(MODEL, SIZE)
);

CREATE TABLE sells (
    DISTRIBUTOR_NAME VARCHAR(100) NOT NULL,
    DISTRIBUTOR_ADDRESS VARCHAR(255) NOT NULL,
    SHOES_MODEL VARCHAR(255) NOT NULL,
    SHOES_SIZE VARCHAR(50) NOT NULL,
    COST DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, SHOES_MODEL, SHOES_SIZE),
    FOREIGN KEY (DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS) REFERENCES distributor(NAME, ADDRESS),
    FOREIGN KEY (SHOES_MODEL, SHOES_SIZE) REFERENCES shoes(MODEL, SIZE)
);

CREATE TABLE contract (
    DISTRIBUTOR_NAME VARCHAR(100) NOT NULL,
    DISTRIBUTOR_ADDRESS VARCHAR(255) NOT NULL,
    MANUFACTURER_NAME VARCHAR(100) NOT NULL,
    COST DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (MANUFACTURER_NAME),
    FOREIGN KEY (DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS) REFERENCES distributor(NAME, ADDRESS),
    FOREIGN KEY (MANUFACTURER_NAME) REFERENCES manufacturer(NAME)
);

CREATE TABLE employs (
    DISTRIBUTOR_NAME VARCHAR(100) NOT NULL,
    DISTRIBUTOR_ADDRESS VARCHAR(255) NOT NULL,
    SALESPERSON_SIN VARCHAR(20) NOT NULL PRIMARY KEY, 
    BASE_SAL DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS) REFERENCES distributor(NAME, ADDRESS),
    FOREIGN KEY (SALESPERSON_SIN) REFERENCES salesperson(SIN)
);




